####################
# WAYTERRA CONFIG IDEA
# WORK IN PROGRESS
mode=apprentice
movement_mode=single_screen
keybinds=basic


################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=eDP-1,1920x1080@60.00300,0x0,1


###################
### MY PROGRAMS ###
###################


# Set programs that you use
$terminal = alacritty
$fileManager = yazi
$menu = rofi -show drun
$wayterraManager = qs


#############################
### ENVIRONMENT VARIABLES ###
#############################



# So firefox can use yazi to open folders
#env = GTK_USE_PORTAL,1


###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow




#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = de

    follow_mouse = 1

    repeat_rate = 35
    repeat_delay = 200
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, Space, exec, $menu
bind = $mainMod, R, exec, $reload_waybar
bind = $mainMod, B, exec, firefox
bind = $mainMod, P, exec, $change_wallpaper
bind = $mainMod SHIFT, L, exec, hyprlock
bind = $mainMod SHIFT, H, exec, $wayterraManager

# Screenshot
bind = , Print, exec, grim -g "$(slurp)" ~/pictures/Screenshot_$(date +%Y%m%d-%H%M%S).png

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
# Also allow vim motions
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d



# Example special workspace (scratchpad)
bind = $mainMod, Plus, togglespecialworkspace, magic
bind = $mainMod SHIFT, Plus, movetoworkspace, special:magic

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
